In [ ]:
import pandas as pd 
import numpy as np 

In [ ]:
dataframe = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data")
print(dataframe.shape)
# chuyển data về dạng numpy 
print(dataframe.head(5))

(32560, 15)
   39          State-gov   77516   Bachelors  ...   0  40   United-States   <=50K
0  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K
1  38            Private  215646     HS-grad  ...   0  40   United-States   <=50K
2  53            Private  234721        11th  ...   0  40   United-States   <=50K
3  28            Private  338409   Bachelors  ...   0  40            Cuba   <=50K
4  37            Private  284582     Masters  ...   0  40   United-States   <=50K

[5 rows x 15 columns]


In [ ]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()
dataframe[' United-States'] = LE.fit_transform(dataframe[' United-States'])
print(dataframe)

       39          State-gov   77516  ...  40   United-States   <=50K
0      50   Self-emp-not-inc   83311  ...  13              39   <=50K
1      38            Private  215646  ...  40              39   <=50K
2      53            Private  234721  ...  40              39   <=50K
3      28            Private  338409  ...  40               5   <=50K
4      37            Private  284582  ...  40              39   <=50K
...    ..                ...     ...  ...  ..             ...     ...
32555  27            Private  257302  ...  38              39   <=50K
32556  40            Private  154374  ...  40              39    >50K
32557  58            Private  151910  ...  40              39   <=50K
32558  22            Private  201490  ...  20              39   <=50K
32559  52       Self-emp-inc  287927  ...  40              39    >50K

[32560 rows x 15 columns]


In [ ]:
# chuyển data về dạng numpy 
data = dataframe.values

In [57]:
a = dataframe.loc[:,['39',' 77516',' 0',' 40',' United-States']]
X = a.values
print(X.shape)
print(X)

(32560, 5)
[[    50  83311      0     13     39]
 [    38 215646      0     40     39]
 [    53 234721      0     40     39]
 ...
 [    58 151910      0     40     39]
 [    22 201490      0     20     39]
 [    52 287927      0     40     39]]


In [58]:
y = data[:,-1]
y.ravel()
print(y.shape)
print(y)

(32560,)
[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' >50K']


In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(\
    X, y, test_size=0.2, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(26048, 5)
(26048,)
Test:
(6512, 5)
(6512,)


In [61]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
# training process
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [62]:
y_pred = model.predict(X_test)

In [63]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       <=50K       0.79      0.85      0.82      4912
        >50K       0.38      0.29      0.33      1600

    accuracy                           0.71      6512
   macro avg       0.58      0.57      0.57      6512
weighted avg       0.69      0.71      0.70      6512



In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[4174,  738],
       [1143,  457]])