**Euclidean**

In [16]:
Height = [5,5.11,5.6,5.9,4.8,5.8,5.3,5.8,5.5,5.6]
Age = [45,26,30,34,40,36,19,28,23,32]
Weight = [77,47,55,59,72,60,40,60,45,58]
label = ['H','L','M','M','H','M','L','M','L','M']
# cho điểm test 
test_a1=5.5
test_a2=38

In [17]:
#Tính khoảng cách
import math

def get_distance(test_a1,test_a2,x,y):
    distance = []
    for i in range(len(x)):
        dis = math.sqrt((x[i]-test_a1)**2 + (y[i]-test_a2)**2)
        distance.append(dis)
    return distance

In [18]:
distance = get_distance(test_a1, test_a2, Height, Age)
for i in range(len(distance)):
    print(distance[i],end=' ')
    print(label[i])

7.0178344238090995 H
12.006335827387138 L
8.000624975587845 M
4.019950248448356 M
2.118962010041709 H
2.0223748416156684 M
19.001052602421794 L
10.004498987955369 M
15.0 L
6.000833275470999 M


In [19]:
import numpy as np
idx = np.argsort(distance)
print(idx)
k = 3
k_idx = idx[:k]
print(k_idx)
for i in k_idx:
    print(label[i],end=' ')

[5 4 3 9 0 2 7 1 8 6]
[5 4 3]
M H M 

**Manhattan**

In [20]:
def get_distance_manhattan(test_a1,test_a2,x,y):
    distance = []
    for i in range(len(x)):
        dis = abs(x[i]-test_a1) + abs(y[i]-test_a2)
        distance.append(dis)
    return distance

In [21]:
distance_m = get_distance_manhattan(test_a1, test_a2, Height, Age)
for i in range(len(distance_m)):
    print(distance_m[i],end=' ')
    print(label[i])

7.5 H
12.39 L
8.1 M
4.4 M
2.7 H
2.3 M
19.2 L
10.3 M
15.0 L
6.1 M


In [32]:
idx = np.argsort(distance_m)
print(idx)
k = 3
k_idx = idx[:k]
print(k_idx)
for i in k_idx:
    print(label[i],end=' ')

[5 4 3 9 0 2 7 1 8 6]
[5 4 3]
M H M 

**Find Weight**

In [33]:
s=0
for i in k_idx:
    s+=Weight[i]
print("Guess Weight with k = 3: ", s/k)    

Guess Weight with k = 3:  63.666666666666664


**Tóm tắt**


```
Khoảng cách Euclidean: Khoảng cách 2 điểm theo trục thẳng.
```
```
Khoảng cách Manhattan: Khoảng cách giữa hai điểm đo dọc theo trục vuông góc. 
```
```
Khi dự liệu cần dự đoán khổng phải label cần sử dụng trung bình cộng.
```
```
KNN được áp dụng vào 2 loại của bài toán Supervised Learning (Classification và Regression).
```
```
Là một thuật toán Instance-based
```